title: The Ok Refusal
email: sumit@sumit-ghosh.com
description: >-
  The Great Refusal, only that it's not so great. Looking for a praxis in this age of disillusionment and discontent.
baseurl: ""
url: "https://okrefusal.com"
twitter_username: summitkg

theme: minima
plugins:
  - jekyll-feed

permalink: /posts/:title/
google_analytics: UA-107859389-2
disqus:
    shortname: okrefusal

headers:
    X-Robots-Tag: noindex

plugins:
  - jekyll-feed
  - jekyll-sitemap
