title: The Ok Refusal
author:
  name: Sumit Ghosh
  email: sumit@sumit-ghosh.com
description: >-
  The Great Refusal, only that it's not so great. Looking for a praxis in this age of disillusionment and discontent.
baseurl: ""
url: "https://okrefusal.com"

minima:
  skin: dark

include:
  - _redirects

remote_theme: jekyll/minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /posts/:title/
google_analytics: UA-107859389-2
disqus:
  shortname: okrefusal
